export { default as Home } from './HomePage';
export { default as Watchlist } from './WatchlistPage';
export { default as Crypto } from './CryptoPage';
export { default as TopCrypto } from './TopCryptoPage';
export { default as TopExchanges } from './TopExchangesPage';
export { default as Rates } from './RatesPage';
export { default as Nft } from './NftPage';
export { default as SignUp } from './SignUpPage';
export { default as SignIn } from './SignInPage';
